server:
  port: 8080
  servlet:
    context-path: /
spring:
  application:
    name: token-service
  redis:
    host: 138.2.86.58
    port: 6379
wechat:
  getToken:
    url: https://api.weixin.qq.com/cgi-bin/token?grant_type=${metadata.grant_type}&appid=${metadata.user}&secret=${metadata.passwd}
  service:
    token: yanwuxu
metadata:
#    user: wxae89e768c22d0fb9
#    passwd: 7a91a9579135de9d42acab9741de0aac
#    grant_type: client_credential
    user: wx60c471b7ee08a6fc
    passwd: e2e4a86965db878dc9ef9f6876257179
    grant_type: client_credential
logging:
  file:
    max-history: 3
    max-size: 10MB
  level:
    com:
      yijian: debug
    feign: debug
  path: /var/log/application/${spring.application.name}
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15}.%M\(%line\)-
            %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15}.%M\(%line\)-
            %msg%n'

