server:
  port: 8080
  servlet:
    context-path: /
spring:
  redis:
    host: 138.2.86.58
    port: 6379
wechat:
  getToken:
    url: https://api.weixin.qq.com/cgi-bin/token?grant_type=${metadata.grant_type}&appid=${metadata.user}&secret=${metadata.passwd}
metadata:
    user: wxae89e768c22d0fb9
    passwd: 7a91a9579135de9d42acab9741de0aac
    grant_type: client_credential
